### ISSUE TITLE
Subscription not working

### ISSUE THREAD

**Issue by mobihunterz** [razorpay/razorpay-woocommerce-subscriptions#18]
I have installed the RazorPay Subscription plugin from Wordpress store and now on Settings->Payment page it shows blue tick for Recurring Payments against RazorPay Subscription plugin.

I have tried using RazorPay for WooCommerce and it's working like a charm. But my main business is to sell subscriptions, I need Recurring payments to be implemented and I feel RazorPay Subscriptions as the last solution to implement the thing.

I have followed the doc full and tried to create Wookbooks on RazorPay Dashboard but it gave me error  like,

`URL must point to a public IP address: http://localhost:8888/skulls/wp-admin/admin-post.php?action=rzp_wc_webhook
`
I have enabled Webhook under WooCommerce -> Settings -> Payment -> RazorPay Plugin.

I googled it and raised question on the main RazorPay WooCommerce github where I found to use ngrok for localhost, so, I did that. I activated ngrok and enabled on 8888 port which I am using. I found it working and got a URL, like, `http://94cbd25b.ngrok.io/`, so, I given this URL in my Webhook,

`http://94cbd25b.ngrok.io/skulls/wp-admin/admin-post.php?action=rzp_wc_webhook`

My Webhook got successfully installed but I am not able to make successful payment as when I hit the URL, it returned me page with error `Error loading page`.

I am not able to resolve this so I turned the Webhook settings off and reinstalled everything.

Now, I am getting error like,

`RAZORPAY ERROR: Subscription creation failed with the following message: 'The total count must be at least 1.'`

However, my subscription is just for 5 years and I don't think this error leads me to correct problem.

Would you let me know how I can integrate Subscriptions for my WooCommerce orders?

I also have created plans on RazorPay with same amount and duration I created as WooCoomerce Subscriptions.

Please let me know how I can get this working for my WooCommerce site.
A proper guide will always be a better help but I am confused over using lots of tutorials and I am also not sure if I need to write code or create any page to support subscriptions. Acually, I don't know how I can customise Order page to plugin RazorPay Subscriptions.

Thank you very much.

**Comment by brijyot** [comment]
I am having the same problem with woocommerce , Did anyone get a solution for this.

**Comment by lbalasub83** [comment]
I am looking for help document like step by step guide to proceed configure in WP. Please help on this.

**Comment by mobihunterz** [comment]
Guys I believe Razorpay does not care of the solution and thats why I opted for Paypal. However, I found something on StackOverFlow which mentioned to limit our subscription for some fixed period of time. Like, subscription will be ending in 5 years or 24 months. Try it.

**Comment by captn3m0** [comment]
This is mentioned on the FAQ for the plugin as well:

>1. We currently do not support lifetime subscriptions as of now. The maximum time that a subscription is allowed to run without requiring an authentication again from the customer is 10 years.

**Comment by ravijordan** [comment]
hi, does the subscription plugin works with Yithy Subscription Plugin. as i am getting error if i am using with this.

**Comment by rajahub108** [comment]
2025 is about to start and this issue is still open. RIP Indian businesses.
