### ISSUE TITLE
RazorPay for Subscriptions is not working with Woocommerce on Wordpress 5.2.1

### ISSUE THREAD

**Issue by docsridhar** [razorpay/razorpay-woocommerce-subscriptions#20]
I am unable to activate RazoPay for subscriptions. I got the below error message:

Fatal error: require_once(): Failed opening required '/srv/htdocs/wp-content/plugins/woo-razorpay/razorpay-payments.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/razorpay-subscriptions-for-woocommerce/razorpay-subscriptions.php on line 27

Earlier the plugin was deactivated by the WorPress team as my site had crashed because of the plugin.

I am using WordPress version 5.2.1

**Comment by captn3m0** [comment]
The subscriptions plugin is currently not supported on the latest release of Razorpay WooCommerce plugin. We plan to do a release that fixes this sometime in June. The last supported release is https://github.com/razorpay/razorpay-woocommerce/releases/tag/v1.6.3

**Comment by m2websolution** [comment]
Hi,
Any update on this now? Its been September and we are still waiting for the update to work with latest version of WooCommerce and Subscribe. 
Thanks

**Comment by prem-techchefs** [comment]
Issue has been fixed and now supported to the latest release of Razorpay Woocommerce plugin, The latest release is
https://github.com/razorpay/razorpay-woocommerce-subscriptions/releases/tag/v2.1.0
