### ISSUE TITLE
Acceptance of other product types

### ISSUE THREAD

**Issue by Meraqi** [razorpay/razorpay-woocommerce-subscriptions#21]
Hello Razorpay Tech Team,

So as discussed with Razorpay Support - here is out issue in detail: 

In WooCommerce there are various product types - Simple Product, Simple Subscription, Variable Subscription and many others - see screenshot attached - Product_Types.png At times we need to create other product types as per the requirement of clients and offer them as subscriptions but Razorpay doesnt allow us to do so. 

In this case we have created a _Product Bundle_ and we are offering that to customers as a subscription. Now the issue is that Razorpay only accepts _Subscription_ Product Type as a subscription product or else it doesnt allow other products to be subscribed to - the error message being attached - error.png.  

To explain better - what we are trying to do is allow the user to create customised product bundle and offer them as subscriptions. WooCommerce Subscriptions accepts this and its showing as subscriptions in the backend - but Razorpay does not and the error message attached.

We basically need a solution where Razorpay allows other product types to be subscribed to as WooCommerce has released an extension where any product can become a subscription. 

Product Example 
https://www.heydaycare.com/subscriptions
Password - 1234

Please help.

Thanks. 

![Product_Types](https://user-images.githubusercontent.com/20583204/58643555-1d471a00-831d-11e9-9d09-c50d3a310155.png)
![Error](https://user-images.githubusercontent.com/20583204/58643556-1d471a00-831d-11e9-95c4-f1caa8acf2b7.png)

**Comment by prem-techchefs** [comment]
Currently razorpay does not support bundled or grouped product. Once we will update this feature in plugin, will push new feature with updated plugin.
