### ISSUE TITLE
Release plugin

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-woocommerce-subscriptions#4]
We've already gotten approval, but need to publish the first release.

The plugin submitted name is `razorpay-subscriptions-for-woocommerce`, which I'm not sure will work. Test the plugin with this name first before publishing.

**Comment by captn3m0** [comment]
Also checklist:

- [ ] Make sure it does not break anything if installed and enabled without its dependencies

**Comment by mayankamencherla** [comment]
Release done. Testing left. https://wordpress.org/plugins/razorpay-subscriptions-for-woocommerce/

**Comment by mayankamencherla** [comment]
Tested fully. Closing issue. Releasing a new plugin.
